version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: denet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  denet:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: denet
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_SSLMODE: disable
    command: sh -c "go-migrate -path /migrations -database postgres://$$DB_USER:$$DB_PASSWORD@$$DB_HOST:$$DB_PORT/$$DB_NAME?sslmode=$$DB_SSLMODE up"

volumes:
  postgres_data: